name: Block direct push to main
on:
  push:
    branches:
      - main

jobs:
  block:
    # só executa se NÃO for um merge de PR via GitHub Web Flow
    if: github.actor != 'web-flow'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Push direto no main bloqueado"
          exit 1
