name: Security Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_CONFIG_PATH: .gitleaks.toml
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 30

  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  security-report:
    name: Security Report
    runs-on: ubuntu-latest
    needs: [gitleaks, dependency-check]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Gitleaks report
        uses: actions/download-artifact@v4
        with:
          name: gitleaks-report
          path: reports/

      - name: Generate security report
        run: |
          echo "# Security Scan Report" > security-report.md
          echo "Generated: $(date)" >> security-report.md
          echo "" >> security-report.md

          if [ -f "reports/gitleaks-report.json" ]; then
            echo "## Secret Detection Results" >> security-report.md
            echo "Gitleaks scan completed. Check the artifacts for detailed results." >> security-report.md
          else
            echo "## Secret Detection Results" >> security-report.md
            echo "✅ No secrets detected in codebase" >> security-report.md
          fi

          echo "" >> security-report.md
          echo "## Test Results" >> security-report.md
          echo "- Logging tests: ${{ needs.logging-tests.result }}" >> security-report.md
          echo "- Dependency check: ${{ needs.dependency-check.result }}" >> security-report.md
          echo "- Secret detection: ${{ needs.gitleaks.result }}" >> security-report.md

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.md
          retention-days: 30
